### ISSUE TITLE
Replace deprecated functions (Make module Drupal 9 compatible)

### ISSUE THREAD

**Issue by normanlolx** [nitin-kawane/custom-form-with-file-upload-in-drupal-8#3]
Replace `drupal_set_message` and adjust the .info.yml file.

[Upgrade Status](https://www.drupal.org/project/upgrade_status) can be a big helper.

Having a module for demonstration purpose it's important to also demonstrate how code is supposed to be written the right way.

**Comment by normanlolx** [comment]
Still not Drupal 9 ready 😿

**Comment by nitin-kawane** [comment]
> Still not Drupal 9 ready 😿

Can you please tell me other issues as well, it will be helpful.
